steps:
  - name: "python:3.10"
    args: ["pip", "install", "-r", "requirements.txt"]
  - name: "python:3.10"
    args: ["python", "manage.py", "migrate"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--quiet"]
options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - version: latest
      secret: blood-bank-442312:us-central1:blood
